#!/usr/bin/env bash

set -euo pipefail

test_suites=(
  "link"
  "add"
)

for test_suite in "${test_suites[@]}"; do
  echo "$test_suite.bash"
  for test in "tests/$test_suite"/*.bash; do
    name=${test##*/}
    echo "  • ${name%.bash}"
    bash "$test"
  done
done
